name: 'CI'

on:
    push:
        branches:
        - master

jobs:
    all_linux:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: 'Packages Installed'
          run: sudo apt update && sudo apt install libcunit1-dev gcovr libsdl2-dev
        - name: 'Compile'
          run: |
            mkdir BuildCI
            cd BuildCI
            cmake ..
            cmake --build .
        - name: 'Testing'
          run: |
            cd BuildCI
            chmod +x *
            ctest -V
        - name: 'Coverage'
          run: |
            cd BuildCI
            chmod +x *
            make cover_html
        - uses: actions/upload-artifact@v1
          with:
            name: CoverageWeb
            path: BuildCI/Covergae